---
created: '2021-03-12T14:08:31.268274Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app-depth-1:
  hash: "a839396425816f4aee5fa6faccdf2dc8"
  tree_label: "`anonymous namespace'::crash"
  component:
    app-depth-1*
      exception*
        stacktrace*
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
app-depth-2:
  hash: "417de9b3a8cc314067366db722a116ca"
  tree_label: "`anonymous namespace'::start | ..."
  component:
    app-depth-2*
      exception*
        stacktrace*
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
app-depth-3:
  hash: "46b84e4da51648cc9f9741abd2bdad51"
  tree_label: "main | `anonymous namespace'::start | ..."
  component:
    app-depth-3*
      exception*
        stacktrace*
          frame*
            filename*
              "main.cpp"
            function*
              "main"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
app-depth-4:
  hash: "2e93ec0f91f97f5211a422d1ab6f7a28"
  tree_label: "invoke_main | main | `anonymous namespace'::start | ..."
  component:
    app-depth-4*
      exception*
        stacktrace*
          frame*
            filename*
              "exe_common.inl"
            function*
              "invoke_main"
          frame*
            filename*
              "main.cpp"
            function*
              "main"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
app-depth-5:
  hash: "15d397771f229af8dc42783542f81dd4"
  tree_label: "__scrt_common_main_seh | invoke_main | main | `anonymous namespace'::start | ..."
  component:
    app-depth-5*
      exception*
        stacktrace*
          frame*
            filename*
              "exe_common.inl"
            function*
              "__scrt_common_main_seh"
          frame*
            filename*
              "exe_common.inl"
            function*
              "invoke_main"
          frame*
            filename*
              "main.cpp"
            function*
              "main"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
app-depth-max:
  hash: "15d397771f229af8dc42783542f81dd4"
  tree_label: "<entire stacktrace>"
  component:
    app-depth-max*
      exception*
        stacktrace*
          frame*
            filename*
              "exe_common.inl"
            function*
              "__scrt_common_main_seh"
          frame*
            filename*
              "exe_common.inl"
            function*
              "invoke_main"
          frame*
            filename*
              "main.cpp"
            function*
              "main"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
--------------------------------------------------------------------------
system:
  hash: "15d397771f229af8dc42783542f81dd4"
  tree_label: "<entire stacktrace>"
  component:
    system*
      exception*
        stacktrace*
          frame*
            filename*
              "exe_common.inl"
            function*
              "__scrt_common_main_seh"
          frame*
            filename*
              "exe_common.inl"
            function*
              "invoke_main"
          frame*
            filename*
              "main.cpp"
            function*
              "main"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::start"
          frame*
            filename*
              "main.cpp"
            function*
              "`anonymous namespace'::crash"
        type (ignored because exception is synthetic)
          "EXCEPTION_ACCESS_VIOLATION_WRITE"
        value (ignored because stacktrace takes precedence)
          "Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE"
